import { Fragment ,Component} from "react";

class TopBar extends Component {
    constructor(props) {
        super(props);
        this.state={
            title:'Morocco',
            language:'Francais',
            countries:{
                
                    "AF": "Afghanistan",
                    "AL": "Albania",
                    "DZ": "Algeria",
                    "AS": "American Samoa",
                    "AD": "Andorra",
                    "AO": "Angola",
                    "AI": "Anguilla",
                    "AQ": "Antarctica",
                    "AG": "Antigua and Barbuda",
                    "AR": "Argentina",
                    "AM": "Armenia",
                    "AW": "Aruba",
                    "AU": "Australia",
                    "AT": "Austria",
                    "AZ": "Azerbaijan",
                    "BS": "Bahamas (the)",
                    "BH": "Bahrain",
                    "BD": "Bangladesh",
                    "BB": "Barbados",
                    "BY": "Belarus",
                    "BE": "Belgium",
                    "BZ": "Belize",
                    "BJ": "Benin",
                    "BM": "Bermuda",
                    "BT": "Bhutan",
                    "BO": "Bolivia (Plurinational State of)",
                    "BQ": "Bonaire, Sint Eustatius and Saba",
                    "BA": "Bosnia and Herzegovina",
                    "BW": "Botswana",
                    "BV": "Bouvet Island",
                    "BR": "Brazil",
                    "IO": "British Indian Ocean Territory (the)",
                    "BN": "Brunei Darussalam",
                    "BG": "Bulgaria",
                    "BF": "Burkina Faso",
                    "BI": "Burundi",
                    "CV": "Cabo Verde",
                    "KH": "Cambodia",
                    "CM": "Cameroon",
                    "CA": "Canada",
                    "KY": "Cayman Islands (the)",
                    "CF": "Central African Republic (the)",
                    "TD": "Chad",
                    "CL": "Chile",
                    "CN": "China",
                    "CX": "Christmas Island",
                    "CC": "Cocos (Keeling) Islands (the)",
                    "CO": "Colombia",
                    "KM": "Comoros (the)",
                    "CD": "Congo (the Democratic Republic of the)",
                    "CG": "Congo (the)",
                    "CK": "Cook Islands (the)",
                    "CR": "Costa Rica",
                    "HR": "Croatia",
                    "CU": "Cuba",
                    "CW": "Curaçao",
                    "CY": "Cyprus",
                    "CZ": "Czechia",
                    "CI": "Côte d'Ivoire",
                    "DK": "Denmark",
                    "DJ": "Djibouti",
                    "DM": "Dominica",
                    "DO": "Dominican Republic (the)",
                    "EC": "Ecuador",
                    "EG": "Egypt",
                    "SV": "El Salvador",
                    "GQ": "Equatorial Guinea",
                    "ER": "Eritrea",
                    "EE": "Estonia",
                    "SZ": "Eswatini",
                    "ET": "Ethiopia",
                    "FK": "Falkland Islands (the) [Malvinas]",
                    "FO": "Faroe Islands (the)",
                    "FJ": "Fiji",
                    "FI": "Finland",
                    "FR": "France",
                    "GF": "French Guiana",
                    "PF": "French Polynesia",
                    "TF": "French Southern Territories (the)",
                    "GA": "Gabon",
                    "GM": "Gambia (the)",
                    "GE": "Georgia",
                    "DE": "Germany",
                    "GH": "Ghana",
                    "GI": "Gibraltar",
                    "GR": "Greece",
                    "GL": "Greenland",
                    "GD": "Grenada",
                    "GP": "Guadeloupe",
                    "GU": "Guam",
                    "GT": "Guatemala",
                    "GG": "Guernsey",
                    "GN": "Guinea",
                    "GW": "Guinea-Bissau",
                    "GY": "Guyana",
                    "HT": "Haiti",
                    "HM": "Heard Island and McDonald Islands",
                    "VA": "Holy See (the)",
                    "HN": "Honduras",
                    "HK": "Hong Kong",
                    "HU": "Hungary",
                    "IS": "Iceland",
                    "IN": "India",
                    "ID": "Indonesia",
                    "IR": "Iran (Islamic Republic of)",
                    "IQ": "Iraq",
                    "IE": "Ireland",
                    "IM": "Isle of Man",
                    "IL": "Israel",
                    "IT": "Italy",
                    "JM": "Jamaica",
                    "JP": "Japan",
                    "JE": "Jersey",
                    "JO": "Jordan",
                    "KZ": "Kazakhstan",
                    "KE": "Kenya",
                    "KI": "Kiribati",
                    "KP": "Korea (the Democratic People's Republic of)",
                    "KR": "Korea (the Republic of)",
                    "KW": "Kuwait",
                    "KG": "Kyrgyzstan",
                    "LA": "Lao People's Democratic Republic (the)",
                    "LV": "Latvia",
                    "LB": "Lebanon",
                    "LS": "Lesotho",
                    "LR": "Liberia",
                    "LY": "Libya",
                    "LI": "Liechtenstein",
                    "LT": "Lithuania",
                    "LU": "Luxembourg",
                    "MO": "Macao",
                    "MG": "Madagascar",
                    "MW": "Malawi",
                    "MY": "Malaysia",
                    "MV": "Maldives",
                    "ML": "Mali",
                    "MT": "Malta",
                    "MH": "Marshall Islands (the)",
                    "MQ": "Martinique",
                    "MR": "Mauritania",
                    "MU": "Mauritius",
                    "YT": "Mayotte",
                    "MX": "Mexico",
                    "FM": "Micronesia (Federated States of)",
                    "MD": "Moldova (the Republic of)",
                    "MC": "Monaco",
                    "MN": "Mongolia",
                    "ME": "Montenegro",
                    "MS": "Montserrat",
                    "MA": "Morocco",
                    "MZ": "Mozambique",
                    "MM": "Myanmar",
                    "NA": "Namibia",
                    "NR": "Nauru",
                    "NP": "Nepal",
                    "NL": "Netherlands (the)",
                    "NC": "New Caledonia",
                    "NZ": "New Zealand",
                    "NI": "Nicaragua",
                    "NE": "Niger (the)",
                    "NG": "Nigeria",
                    "NU": "Niue",
                    "NF": "Norfolk Island",
                    "MP": "Northern Mariana Islands (the)",
                    "NO": "Norway",
                    "OM": "Oman",
                    "PK": "Pakistan",
                    "PW": "Palau",
                    "PS": "Palestine, State of",
                    "PA": "Panama",
                    "PG": "Papua New Guinea",
                    "PY": "Paraguay",
                    "PE": "Peru",
                    "PH": "Philippines (the)",
                    "PN": "Pitcairn",
                    "PL": "Poland",
                    "PT": "Portugal",
                    "PR": "Puerto Rico",
                    "QA": "Qatar",
                    "MK": "Republic of North Macedonia",
                    "RO": "Romania",
                    "RU": "Russian Federation (the)",
                    "RW": "Rwanda",
                    "RE": "Réunion",
                    "BL": "Saint Barthélemy",
                    "SH": "Saint Helena, Ascension and Tristan da Cunha",
                    "KN": "Saint Kitts and Nevis",
                    "LC": "Saint Lucia",
                    "MF": "Saint Martin (French part)",
                    "PM": "Saint Pierre and Miquelon",
                    "VC": "Saint Vincent and the Grenadines",
                    "WS": "Samoa",
                    "SM": "San Marino",
                    "ST": "Sao Tome and Principe",
                    "SA": "Saudi Arabia",
                    "SN": "Senegal",
                    "RS": "Serbia",
                    "SC": "Seychelles",
                    "SL": "Sierra Leone",
                    "SG": "Singapore",
                    "SX": "Sint Maarten (Dutch part)",
                    "SK": "Slovakia",
                    "SI": "Slovenia",
                    "SB": "Solomon Islands",
                    "SO": "Somalia",
                    "ZA": "South Africa",
                    "GS": "South Georgia and the South Sandwich Islands",
                    "SS": "South Sudan",
                    "ES": "Spain",
                    "LK": "Sri Lanka",
                    "SD": "Sudan (the)",
                    "SR": "Suriname",
                    "SJ": "Svalbard and Jan Mayen",
                    "SE": "Sweden",
                    "CH": "Switzerland",
                    "SY": "Syrian Arab Republic",
                    "TW": "Taiwan",
                    "TJ": "Tajikistan",
                    "TZ": "Tanzania, United Republic of",
                    "TH": "Thailand",
                    "TL": "Timor-Leste",
                    "TG": "Togo",
                    "TK": "Tokelau",
                    "TO": "Tonga",
                    "TT": "Trinidad and Tobago",
                    "TN": "Tunisia",
                    "TR": "Turkey",
                    "TM": "Turkmenistan",
                    "TC": "Turks and Caicos Islands (the)",
                    "TV": "Tuvalu",
                    "UG": "Uganda",
                    "UA": "Ukraine",
                    "AE": "United Arab Emirates (the)",
                    "GB": "United Kingdom of Great Britain and Northern Ireland (the)",
                    "UM": "United States Minor Outlying Islands (the)",
                    "US": "United States of America (the)",
                    "UY": "Uruguay",
                    "UZ": "Uzbekistan",
                    "VU": "Vanuatu",
                    "VE": "Venezuela (Bolivarian Republic of)",
                    "VN": "Viet Nam",
                    "VG": "Virgin Islands (British)",
                    "VI": "Virgin Islands (U.S.)",
                    "WF": "Wallis and Futuna",
                    "EH": "Western Sahara",
                    "YE": "Yemen",
                    "ZM": "Zambia",
                    "ZW": "Zimbabwe",
                    "AX": "Åland Islands" 
            },
            langCodesCopy:{
                "af":    "Afrikaans",
                "sq":    "Albanian",
                "an":    "Aragonese",
                "ar":    "Arabic (Standard)",
                "ar-dz": "Arabic (Algeria)",
                "ar-bh": "Arabic (Bahrain)",
                "ar-eg": "Arabic (Egypt)",
                "ar-iq": "Arabic (Iraq)",
                "ar-jo": "Arabic (Jordan)",
                "ar-kw": "Arabic (Kuwait)",
                "ar-lb": "Arabic (Lebanon)",
                "ar-ly": "Arabic (Libya)",
                "ar-ma": "Arabic (Morocco)",
                "ar-om": "Arabic (Oman)",
                "ar-qa": "Arabic (Qatar)",
                "ar-sa": "Arabic (Saudi Arabia)",
                "ar-sy": "Arabic (Syria)",
                "ar-tn": "Arabic (Tunisia)",
                "ar-ae": "Arabic (U.A.E.)",
                "ar-ye": "Arabic (Yemen)",
                "hy":    "Armenian",
                "as":    "Assamese",
                "ast":   "Asturian",
                "az":    "Azerbaijani",
                "eu":    "Basque",
                "bg":    "Bulgarian",
                "be":    "Belarusian",
                "bn":    "Bengali",
                "bs":    "Bosnian",
                "br":    "Breton",
                "bg":    "Bulgarian",
                "my":    "Burmese",
                "ca":    "Catalan",
                "ch":    "Chamorro",
                "ce":    "Chechen",
                "zh":    "Chinese",
                "zh-hk": "Chinese (Hong Kong)",
                "zh-cn": "Chinese (PRC)",
                "zh-sg": "Chinese (Singapore)",
                "zh-tw": "Chinese (Taiwan)",
                "cv":    "Chuvash",
                "co":    "Corsican",
                "cr":    "Cree",
                "hr":    "Croatian",
                "cs":    "Czech",
                "da":    "Danish",
                "nl":    "Dutch (Standard)",
                "nl-be": "Dutch (Belgian)",
                "en":    "English",
                "en-au": "English (Australia)",
                "en-bz": "English (Belize)",
                "en-ca": "English (Canada)",
                "en-ie": "English (Ireland)",
                "en-jm": "English (Jamaica)",
                "en-nz": "English (New Zealand)",
                "en-ph": "English (Philippines)",
                "en-za": "English (South Africa)",
                "en-tt": "English (Trinidad & Tobago)",
                "en-gb": "English (United Kingdom)",
                "en-us": "English (United States)",
                "en-zw": "English (Zimbabwe)",
                "eo":    "Esperanto",
                "et":    "Estonian",
                "fo":    "Faeroese",
                "fa":    "Farsi",
                "fj":    "Fijian",
                "fi":    "Finnish",
                "fr":    "French (Standard)",
                "fr-be": "French (Belgium)",
                "fr-ca": "French (Canada)",
                "fr-fr": "French (France)",
                "fr-lu": "French (Luxembourg)",
                "fr-mc": "French (Monaco)",
                "fr-ch": "French (Switzerland)",
                "fy":    "Frisian",
                "fur":   "Friulian",
                "gd":    "Gaelic (Scots)",
                "gd-ie": "Gaelic (Irish)",
                "gl":    "Galacian",
                "ka":    "Georgian",
                "de":    "German (Standard)",
                "de-at": "German (Austria)",
                "de-de": "German (Germany)",
                "de-li": "German (Liechtenstein)",
                "de-lu": "German (Luxembourg)",
                "de-ch": "German (Switzerland)",
                "el":    "Greek",
                "gu":    "Gujurati",
                "ht":    "Haitian",
                "he":    "Hebrew",
                "hi":    "Hindi",
                "hu":    "Hungarian",
                "is":    "Icelandic",
                "id":    "Indonesian",
                "iu":    "Inuktitut",
                "ga":    "Irish",
                "it":    "Italian (Standard)",
                "it-ch": "Italian (Switzerland)",
                "ja":    "Japanese",
                "kn":    "Kannada",
                "ks":    "Kashmiri",
                "kk":    "Kazakh",
                "km":    "Khmer",
                "ky":    "Kirghiz",
                "tlh":   "Klingon",
                "ko":    "Korean",
                "ko-kp": "Korean (North Korea)",
                "ko-kr": "Korean (South Korea)",
                "la":    "Latin",
                "lv":    "Latvian",
                "lt":    "Lithuanian",
                "lb":    "Luxembourgish",
                "mk":    "FYRO Macedonian",
                "ms":    "Malay",
                "ml":    "Malayalam",
                "mt":    "Maltese",
                "mi":    "Maori",
                "mr":    "Marathi",
                "mo":    "Moldavian",
                "nv":    "Navajo",
                "ng":    "Ndonga",
                "ne":    "Nepali",
                "no":    "Norwegian",
                "nb":    "Norwegian (Bokmal)",
                "nn":    "Norwegian (Nynorsk)",
                "oc":    "Occitan",
                "or":    "Oriya",
                "om":    "Oromo",
                "fa":    "Persian",
                "fa-ir": "Persian/Iran",
                "pl":    "Polish",
                "pt":    "Portuguese",
                "pt-br": "Portuguese (Brazil)",
                "pa":    "Punjabi",
                "pa-in": "Punjabi (India)",
                "pa-pk": "Punjabi (Pakistan)",
                "qu":    "Quechua",
                "rm":    "Rhaeto-Romanic",
                "ro":    "Romanian",
                "ro-mo": "Romanian (Moldavia)",
                "ru":    "Russian",
                "ru-mo": "Russian (Moldavia)",
                "sz":    "Sami (Lappish)",
                "sg":    "Sango",
                "sa":    "Sanskrit",
                "sc":    "Sardinian",
                "gd":    "Scots Gaelic",
                "sd":    "Sindhi",
                "si":    "Singhalese",
                "sr":    "Serbian",
                "sk":    "Slovak",
                "sl":    "Slovenian",
                "so":    "Somani",
                "sb":    "Sorbian",
                "es":    "Spanish",
                "es-ar": "Spanish (Argentina)",
                "es-bo": "Spanish (Bolivia)",
                "es-cl": "Spanish (Chile)",
                "es-co": "Spanish (Colombia)",
                "es-cr": "Spanish (Costa Rica)",
                "es-do": "Spanish (Dominican Republic)",
                "es-ec": "Spanish (Ecuador)",
                "es-sv": "Spanish (El Salvador)",
                "es-gt": "Spanish (Guatemala)",
                "es-hn": "Spanish (Honduras)",
                "es-mx": "Spanish (Mexico)",
                "es-ni": "Spanish (Nicaragua)",
                "es-pa": "Spanish (Panama)",
                "es-py": "Spanish (Paraguay)",
                "es-pe": "Spanish (Peru)",
                "es-pr": "Spanish (Puerto Rico)",
                "es-es": "Spanish (Spain)",
                "es-uy": "Spanish (Uruguay)",
                "es-ve": "Spanish (Venezuela)",
                "sx":    "Sutu",
                "sw":    "Swahili",
                "sv":    "Swedish",
                "sv-fi": "Swedish (Finland)",
                "sv-sv": "Swedish (Sweden)",
                "ta":    "Tamil",
                "tt":    "Tatar",
                "te":    "Teluga",
                "th":    "Thai",
                "tig":   "Tigre",
                "ts":    "Tsonga",
                "tn":    "Tswana",
                "tr":    "Turkish",
                "tk":    "Turkmen",
                "uk":    "Ukrainian",
                "hsb":   "Upper Sorbian",
                "ur":    "Urdu",
                "ve":    "Venda",
                "vi":    "Vietnamese",
                "vo":    "Volapuk",
                "wa":    "Walloon",
                "cy":    "Welsh",
                "xh":    "Xhosa",
                "ji":    "Yiddish",
                "zu":    "Zulu",
            },
            langCodes :{
                "af":    "Afrikaans",
                "sq":    "Albanian",
                "an":    "Aragonese",
                "ar":    "Arabic (Standard)",
                "ar-dz": "Arabic (Algeria)",
                "ar-bh": "Arabic (Bahrain)",
                "ar-eg": "Arabic (Egypt)",
                "ar-iq": "Arabic (Iraq)",
                "ar-jo": "Arabic (Jordan)",
                "ar-kw": "Arabic (Kuwait)",
                "ar-lb": "Arabic (Lebanon)",
                "ar-ly": "Arabic (Libya)",
                "ar-ma": "Arabic (Morocco)",
                "ar-om": "Arabic (Oman)",
                "ar-qa": "Arabic (Qatar)",
                "ar-sa": "Arabic (Saudi Arabia)",
                "ar-sy": "Arabic (Syria)",
                "ar-tn": "Arabic (Tunisia)",
                "ar-ae": "Arabic (U.A.E.)",
                "ar-ye": "Arabic (Yemen)",
                "hy":    "Armenian",
                "as":    "Assamese",
                "ast":   "Asturian",
                "az":    "Azerbaijani",
                "eu":    "Basque",
                "bg":    "Bulgarian",
                "be":    "Belarusian",
                "bn":    "Bengali",
                "bs":    "Bosnian",
                "br":    "Breton",
                "bg":    "Bulgarian",
                "my":    "Burmese",
                "ca":    "Catalan",
                "ch":    "Chamorro",
                "ce":    "Chechen",
                "zh":    "Chinese",
                "zh-hk": "Chinese (Hong Kong)",
                "zh-cn": "Chinese (PRC)",
                "zh-sg": "Chinese (Singapore)",
                "zh-tw": "Chinese (Taiwan)",
                "cv":    "Chuvash",
                "co":    "Corsican",
                "cr":    "Cree",
                "hr":    "Croatian",
                "cs":    "Czech",
                "da":    "Danish",
                "nl":    "Dutch (Standard)",
                "nl-be": "Dutch (Belgian)",
                "en":    "English",
                "en-au": "English (Australia)",
                "en-bz": "English (Belize)",
                "en-ca": "English (Canada)",
                "en-ie": "English (Ireland)",
                "en-jm": "English (Jamaica)",
                "en-nz": "English (New Zealand)",
                "en-ph": "English (Philippines)",
                "en-za": "English (South Africa)",
                "en-tt": "English (Trinidad & Tobago)",
                "en-gb": "English (United Kingdom)",
                "en-us": "English (United States)",
                "en-zw": "English (Zimbabwe)",
                "eo":    "Esperanto",
                "et":    "Estonian",
                "fo":    "Faeroese",
                "fa":    "Farsi",
                "fj":    "Fijian",
                "fi":    "Finnish",
                "fr":    "French (Standard)",
                "fr-be": "French (Belgium)",
                "fr-ca": "French (Canada)",
                "fr-fr": "French (France)",
                "fr-lu": "French (Luxembourg)",
                "fr-mc": "French (Monaco)",
                "fr-ch": "French (Switzerland)",
                "fy":    "Frisian",
                "fur":   "Friulian",
                "gd":    "Gaelic (Scots)",
                "gd-ie": "Gaelic (Irish)",
                "gl":    "Galacian",
                "ka":    "Georgian",
                "de":    "German (Standard)",
                "de-at": "German (Austria)",
                "de-de": "German (Germany)",
                "de-li": "German (Liechtenstein)",
                "de-lu": "German (Luxembourg)",
                "de-ch": "German (Switzerland)",
                "el":    "Greek",
                "gu":    "Gujurati",
                "ht":    "Haitian",
                "he":    "Hebrew",
                "hi":    "Hindi",
                "hu":    "Hungarian",
                "is":    "Icelandic",
                "id":    "Indonesian",
                "iu":    "Inuktitut",
                "ga":    "Irish",
                "it":    "Italian (Standard)",
                "it-ch": "Italian (Switzerland)",
                "ja":    "Japanese",
                "kn":    "Kannada",
                "ks":    "Kashmiri",
                "kk":    "Kazakh",
                "km":    "Khmer",
                "ky":    "Kirghiz",
                "tlh":   "Klingon",
                "ko":    "Korean",
                "ko-kp": "Korean (North Korea)",
                "ko-kr": "Korean (South Korea)",
                "la":    "Latin",
                "lv":    "Latvian",
                "lt":    "Lithuanian",
                "lb":    "Luxembourgish",
                "mk":    "FYRO Macedonian",
                "ms":    "Malay",
                "ml":    "Malayalam",
                "mt":    "Maltese",
                "mi":    "Maori",
                "mr":    "Marathi",
                "mo":    "Moldavian",
                "nv":    "Navajo",
                "ng":    "Ndonga",
                "ne":    "Nepali",
                "no":    "Norwegian",
                "nb":    "Norwegian (Bokmal)",
                "nn":    "Norwegian (Nynorsk)",
                "oc":    "Occitan",
                "or":    "Oriya",
                "om":    "Oromo",
                "fa":    "Persian",
                "fa-ir": "Persian/Iran",
                "pl":    "Polish",
                "pt":    "Portuguese",
                "pt-br": "Portuguese (Brazil)",
                "pa":    "Punjabi",
                "pa-in": "Punjabi (India)",
                "pa-pk": "Punjabi (Pakistan)",
                "qu":    "Quechua",
                "rm":    "Rhaeto-Romanic",
                "ro":    "Romanian",
                "ro-mo": "Romanian (Moldavia)",
                "ru":    "Russian",
                "ru-mo": "Russian (Moldavia)",
                "sz":    "Sami (Lappish)",
                "sg":    "Sango",
                "sa":    "Sanskrit",
                "sc":    "Sardinian",
                "gd":    "Scots Gaelic",
                "sd":    "Sindhi",
                "si":    "Singhalese",
                "sr":    "Serbian",
                "sk":    "Slovak",
                "sl":    "Slovenian",
                "so":    "Somani",
                "sb":    "Sorbian",
                "es":    "Spanish",
                "es-ar": "Spanish (Argentina)",
                "es-bo": "Spanish (Bolivia)",
                "es-cl": "Spanish (Chile)",
                "es-co": "Spanish (Colombia)",
                "es-cr": "Spanish (Costa Rica)",
                "es-do": "Spanish (Dominican Republic)",
                "es-ec": "Spanish (Ecuador)",
                "es-sv": "Spanish (El Salvador)",
                "es-gt": "Spanish (Guatemala)",
                "es-hn": "Spanish (Honduras)",
                "es-mx": "Spanish (Mexico)",
                "es-ni": "Spanish (Nicaragua)",
                "es-pa": "Spanish (Panama)",
                "es-py": "Spanish (Paraguay)",
                "es-pe": "Spanish (Peru)",
                "es-pr": "Spanish (Puerto Rico)",
                "es-es": "Spanish (Spain)",
                "es-uy": "Spanish (Uruguay)",
                "es-ve": "Spanish (Venezuela)",
                "sx":    "Sutu",
                "sw":    "Swahili",
                "sv":    "Swedish",
                "sv-fi": "Swedish (Finland)",
                "sv-sv": "Swedish (Sweden)",
                "ta":    "Tamil",
                "tt":    "Tatar",
                "te":    "Teluga",
                "th":    "Thai",
                "tig":   "Tigre",
                "ts":    "Tsonga",
                "tn":    "Tswana",
                "tr":    "Turkish",
                "tk":    "Turkmen",
                "uk":    "Ukrainian",
                "hsb":   "Upper Sorbian",
                "ur":    "Urdu",
                "ve":    "Venda",
                "vi":    "Vietnamese",
                "vo":    "Volapuk",
                "wa":    "Walloon",
                "cy":    "Welsh",
                "xh":    "Xhosa",
                "ji":    "Yiddish",
                "zu":    "Zulu",
            },
            countriesCopy:{
                
                "AF": "Afghanistan",
                "AL": "Albania",
                "DZ": "Algeria",
                "AS": "American Samoa",
                "AD": "Andorra",
                "AO": "Angola",
                "AI": "Anguilla",
                "AQ": "Antarctica",
                "AG": "Antigua and Barbuda",
                "AR": "Argentina",
                "AM": "Armenia",
                "AW": "Aruba",
                "AU": "Australia",
                "AT": "Austria",
                "AZ": "Azerbaijan",
                "BS": "Bahamas (the)",
                "BH": "Bahrain",
                "BD": "Bangladesh",
                "BB": "Barbados",
                "BY": "Belarus",
                "BE": "Belgium",
                "BZ": "Belize",
                "BJ": "Benin",
                "BM": "Bermuda",
                "BT": "Bhutan",
                "BO": "Bolivia (Plurinational State of)",
                "BQ": "Bonaire, Sint Eustatius and Saba",
                "BA": "Bosnia and Herzegovina",
                "BW": "Botswana",
                "BV": "Bouvet Island",
                "BR": "Brazil",
                "IO": "British Indian Ocean Territory (the)",
                "BN": "Brunei Darussalam",
                "BG": "Bulgaria",
                "BF": "Burkina Faso",
                "BI": "Burundi",
                "CV": "Cabo Verde",
                "KH": "Cambodia",
                "CM": "Cameroon",
                "CA": "Canada",
                "KY": "Cayman Islands (the)",
                "CF": "Central African Republic (the)",
                "TD": "Chad",
                "CL": "Chile",
                "CN": "China",
                "CX": "Christmas Island",
                "CC": "Cocos (Keeling) Islands (the)",
                "CO": "Colombia",
                "KM": "Comoros (the)",
                "CD": "Congo (the Democratic Republic of the)",
                "CG": "Congo (the)",
                "CK": "Cook Islands (the)",
                "CR": "Costa Rica",
                "HR": "Croatia",
                "CU": "Cuba",
                "CW": "Curaçao",
                "CY": "Cyprus",
                "CZ": "Czechia",
                "CI": "Côte d'Ivoire",
                "DK": "Denmark",
                "DJ": "Djibouti",
                "DM": "Dominica",
                "DO": "Dominican Republic (the)",
                "EC": "Ecuador",
                "EG": "Egypt",
                "SV": "El Salvador",
                "GQ": "Equatorial Guinea",
                "ER": "Eritrea",
                "EE": "Estonia",
                "SZ": "Eswatini",
                "ET": "Ethiopia",
                "FK": "Falkland Islands (the) [Malvinas]",
                "FO": "Faroe Islands (the)",
                "FJ": "Fiji",
                "FI": "Finland",
                "FR": "France",
                "GF": "French Guiana",
                "PF": "French Polynesia",
                "TF": "French Southern Territories (the)",
                "GA": "Gabon",
                "GM": "Gambia (the)",
                "GE": "Georgia",
                "DE": "Germany",
                "GH": "Ghana",
                "GI": "Gibraltar",
                "GR": "Greece",
                "GL": "Greenland",
                "GD": "Grenada",
                "GP": "Guadeloupe",
                "GU": "Guam",
                "GT": "Guatemala",
                "GG": "Guernsey",
                "GN": "Guinea",
                "GW": "Guinea-Bissau",
                "GY": "Guyana",
                "HT": "Haiti",
                "HM": "Heard Island and McDonald Islands",
                "VA": "Holy See (the)",
                "HN": "Honduras",
                "HK": "Hong Kong",
                "HU": "Hungary",
                "IS": "Iceland",
                "IN": "India",
                "ID": "Indonesia",
                "IR": "Iran (Islamic Republic of)",
                "IQ": "Iraq",
                "IE": "Ireland",
                "IM": "Isle of Man",
                "IL": "Israel",
                "IT": "Italy",
                "JM": "Jamaica",
                "JP": "Japan",
                "JE": "Jersey",
                "JO": "Jordan",
                "KZ": "Kazakhstan",
                "KE": "Kenya",
                "KI": "Kiribati",
                "KP": "Korea (the Democratic People's Republic of)",
                "KR": "Korea (the Republic of)",
                "KW": "Kuwait",
                "KG": "Kyrgyzstan",
                "LA": "Lao People's Democratic Republic (the)",
                "LV": "Latvia",
                "LB": "Lebanon",
                "LS": "Lesotho",
                "LR": "Liberia",
                "LY": "Libya",
                "LI": "Liechtenstein",
                "LT": "Lithuania",
                "LU": "Luxembourg",
                "MO": "Macao",
                "MG": "Madagascar",
                "MW": "Malawi",
                "MY": "Malaysia",
                "MV": "Maldives",
                "ML": "Mali",
                "MT": "Malta",
                "MH": "Marshall Islands (the)",
                "MQ": "Martinique",
                "MR": "Mauritania",
                "MU": "Mauritius",
                "YT": "Mayotte",
                "MX": "Mexico",
                "FM": "Micronesia (Federated States of)",
                "MD": "Moldova (the Republic of)",
                "MC": "Monaco",
                "MN": "Mongolia",
                "ME": "Montenegro",
                "MS": "Montserrat",
                "MA": "Morocco",
                "MZ": "Mozambique",
                "MM": "Myanmar",
                "NA": "Namibia",
                "NR": "Nauru",
                "NP": "Nepal",
                "NL": "Netherlands (the)",
                "NC": "New Caledonia",
                "NZ": "New Zealand",
                "NI": "Nicaragua",
                "NE": "Niger (the)",
                "NG": "Nigeria",
                "NU": "Niue",
                "NF": "Norfolk Island",
                "MP": "Northern Mariana Islands (the)",
                "NO": "Norway",
                "OM": "Oman",
                "PK": "Pakistan",
                "PW": "Palau",
                "PS": "Palestine, State of",
                "PA": "Panama",
                "PG": "Papua New Guinea",
                "PY": "Paraguay",
                "PE": "Peru",
                "PH": "Philippines (the)",
                "PN": "Pitcairn",
                "PL": "Poland",
                "PT": "Portugal",
                "PR": "Puerto Rico",
                "QA": "Qatar",
                "MK": "Republic of North Macedonia",
                "RO": "Romania",
                "RU": "Russian Federation (the)",
                "RW": "Rwanda",
                "RE": "Réunion",
                "BL": "Saint Barthélemy",
                "SH": "Saint Helena, Ascension and Tristan da Cunha",
                "KN": "Saint Kitts and Nevis",
                "LC": "Saint Lucia",
                "MF": "Saint Martin (French part)",
                "PM": "Saint Pierre and Miquelon",
                "VC": "Saint Vincent and the Grenadines",
                "WS": "Samoa",
                "SM": "San Marino",
                "ST": "Sao Tome and Principe",
                "SA": "Saudi Arabia",
                "SN": "Senegal",
                "RS": "Serbia",
                "SC": "Seychelles",
                "SL": "Sierra Leone",
                "SG": "Singapore",
                "SX": "Sint Maarten (Dutch part)",
                "SK": "Slovakia",
                "SI": "Slovenia",
                "SB": "Solomon Islands",
                "SO": "Somalia",
                "ZA": "South Africa",
                "GS": "South Georgia and the South Sandwich Islands",
                "SS": "South Sudan",
                "ES": "Spain",
                "LK": "Sri Lanka",
                "SD": "Sudan (the)",
                "SR": "Suriname",
                "SJ": "Svalbard and Jan Mayen",
                "SE": "Sweden",
                "CH": "Switzerland",
                "SY": "Syrian Arab Republic",
                "TW": "Taiwan",
                "TJ": "Tajikistan",
                "TZ": "Tanzania, United Republic of",
                "TH": "Thailand",
                "TL": "Timor-Leste",
                "TG": "Togo",
                "TK": "Tokelau",
                "TO": "Tonga",
                "TT": "Trinidad and Tobago",
                "TN": "Tunisia",
                "TR": "Turkey",
                "TM": "Turkmenistan",
                "TC": "Turks and Caicos Islands (the)",
                "TV": "Tuvalu",
                "UG": "Uganda",
                "UA": "Ukraine",
                "AE": "United Arab Emirates (the)",
                "GB": "United Kingdom of Great Britain and Northern Ireland (the)",
                "UM": "United States Minor Outlying Islands (the)",
                "US": "United States of America (the)",
                "UY": "Uruguay",
                "UZ": "Uzbekistan",
                "VU": "Vanuatu",
                "VE": "Venezuela (Bolivarian Republic of)",
                "VN": "Viet Nam",
                "VG": "Virgin Islands (British)",
                "VI": "Virgin Islands (U.S.)",
                "WF": "Wallis and Futuna",
                "EH": "Western Sahara",
                "YE": "Yemen",
                "ZM": "Zambia",
                "ZW": "Zimbabwe",
                "AX": "Åland Islands" 
        },
        show:true,
            
        }
        this.filterCountries=this.filterCountries.bind(this)
       this.setContry=this.setContry.bind(this)
       this.setLang=this.setLang.bind(this)
       this.filterLang=this.filterLang.bind(this)
       this.hide=this.hide.bind(this)
    }

    state = {  }
    filterCountries(event){
        
        
        const newCountries = Object.keys(this.state.countries).reduce((result, item) => {
            if (this.state.countries[item].toLowerCase().includes(event.target.value.toLowerCase())) {
              result[item] = this.state.countries[item];
            }
            return result;
          }, {});
        
        this.setState({countriesCopy:newCountries})
       

    }
    setContry(event,code){
        var country=this.state.countries[code];
        this.setState({title:country})
        this.props.toggle2()

    }
    filterLang(event){
        const newLan = Object.keys(this.state.langCodes).reduce((result, item) => {
            if (this.state.langCodes[item].toLowerCase().includes(event.target.value.toLowerCase())) {
              result[item] = this.state.langCodes[item];
            }
            return result;
          }, {});
        
        this.setState({langCodesCopy:newLan})
    }
    setLang(eveny ,code){
        var lan=this.state.langCodes[code];
        this.setState({language:lan})
        this.props.toggle2()
    }
    hide(){
        this.setState({show:false})
    }
    render() { 
        return ( 
            <Fragment>
                <div className="nav_mobile"></div>
                {this.state.show &&
                <div className="TopBar" >
                    <div className="content">
                        <p>Définissez votre emplacement et votre langue pour donner la priorité aux informations localisées.</p>
                           <div className="contentBtton">
                                <div className="dropdown-with-search-container">
                                        <button>
                                            <div className="Title">{this.state.title}</div>
                                            <div className="btnIcon" onClick={this.props.toggle1}><i className="fa-solid fa-chevron-down"></i></div>
                                        </button>
                                        {this.props.check1
                                         &&
                                         <div className="dropdown">
                                            <p className="droptitle">Emplacement du projet</p>
                                            <p className="usage">Définissez l'emplacement de votre projet pour afficher les produits et les marques disponibles dans votre région.</p>
                                            <input type="search" name="" id="" placeholder="search"onChange={this.filterCountries}/>
                                            <div className="listes">
                                                <ul>
                                                {Object.keys(this.state.countriesCopy).map((code, index) => (
                                                    <li key={index} className="mr-16" onClick={(event)=>this.setContry(event,code)}>
                                                        <img src={`https://flagcdn.com/48x36/${code.toLowerCase()}.png`} alt="..." /><span>{this.state.countriesCopy[code]}</span>
                                                    </li>
                                                ))}
                                                </ul>
                                            </div>
                                         </div>
                                         }
                                </div>
                                <div className="dropdown-with-search-container">
                                        <button>
                                            <div className="Title">{this.state.language}</div>
                                            <div className="btnIcon" onClick={this.props.toggle2}><i className="fa-solid fa-chevron-down"></i></div>
                                        </button>
                                        {this.props.check2 && 
                                        
                                                <div className="dropdown">
                                                            <p className="droptitle">Langue</p>
                                                            {/* <p className="usage">Définissez l'emplacement de votre projet pour afficher les produits et les marques disponibles dans votre région.</p> */}
                                                            <input type="search" name="" id="" placeholder="search" onChange={this.filterLang}/>
                                                            <div className="listes lang" >
                                                                <ul>
                                                                {Object.keys(this.state.langCodesCopy).map((code, index) => (
                                                                    <li key={index} className="mr-16" onClick={(event)=>this.setLang(event,code)}>
                                                                        <span>{this.state.langCodesCopy[code]}</span>
                                                                    </li>
                                                                ))}
                                                                </ul>
                                                            </div>
                                                </div>
                                        }

                                </div>
                            <button className="continue">continue</button>
                            </div>
                    </div>
                    <i className="fa fa-times" onClick={this.hide} ></i>
                </div>
                }
            </Fragment>
         );
    }
}
 
export default TopBar;